### ISSUE TITLE
When I start training, codes freeze my computer.

### ISSUE THREAD

**Issue by MonsKim999** [jialinwu17/generate_captions_for_vqa#1]
How to solve it?
I suffer from this problem for the first time.
Other codes on my computer work well.

Thank you.

**Comment by MonsKim999** [comment]
I solve it. this is data-parallel problem.
I replaced it with unimodal. 
Could you fix this issue?

**Comment by jialinwu17** [comment]
I think we do need data parallel especially in the stage of training captioned

**Comment by MonsKim999** [comment]
Could I know the requirements?
pytorch, cuda, python, torchvision, tqdm. version..

Thank you!

**Comment by jialinwu17** [comment]
Hi,
I attach the txt file containing all my packages' versions by conda list. Hope that helps.
[version.txt](https://github.com/jialinwu17/generate_captions_for_vqa/files/3690838/version.txt)

**Comment by MonsKim999** [comment]
Thank you for your kind response.
I solved this issue.
I used ubuntu 18.04. so if I use the data-parallel model, this code freezes my computer.
I recommend using 16.04. 
the requirement is the same as @jialinwu17
